name: Build HAKRC
on:
  workflow_dispatch: # Libera o botão "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install ninja-build
      - name: Build HAKRC F722V2
        run: |
          mkdir -p build && cd build
          cmake -DTARGET=HAKRCF722V2 -G Ninja ..
          ninja HAKRCF722V2
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HAKRCF722V2_Custom
          path: ./build/*.hex
