name: Build Firmware
on:
  workflow_dispatch: # Libera o botão "Run workflow"
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Toolchain
        run: sudo apt-get update && sudo apt-get -y install gcc-arm-none-eabi ninja-build
      - name: Build HAKRC F722V2
        run: |
          mkdir build && cd build
          cmake -DTARGET=HAKRCF722V2 -G Ninja ..
          ninja HAKRCF722V2
      - name: Upload Hex
        uses: actions/upload-artifact@v4
        with:
          name: Firmware_HAKRC
          path: ./build/*.hex
